import SmoothScroll from "@/components/SmoothScroll";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Hasib Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          <Navbar />
          {children}

          <Toaster />
        </SmoothScroll>
      </body>
    </html>
  );
}
